[project]
name = "company-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.2",
    "asyncpg>=0.31.0",
    "langchain>=1.4.0",
    "langchain-chroma>=1.1.0",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.2",
    "langchain-google-genai>=4.4.0",
    "psycopg[binary]>=3.3.5",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.52",
]
